### ISSUE TITLE
Can't log in to demo

### ISSUE THREAD

**Issue by parakats** [failys/persona_helper#6]
Trying to log in to the demo site the page just reloads with no error message

**Comment by failys** [comment]
I've just tried connecting to the live demo (https://demo.cairis.org) from the persona helper, and can add a factoid without any problem.  As such, I'm closing this issue for now, as I can't see anything amiss.  When connecting, ensure you provide the full URL (i.e. with the https:// prefix).  This has caused problems with people connecting from the live demo in the past.
